---
project: hpa_challenge
task: classification
log_path: /home/kolinko/logs/cam/

devices:
  - 'cuda:1'

train:
  path: &TRAIN_PATH /datasets/kolinko/hpa
  transform:
    size: &SIZE 512
    augmentation_scope: weak
    images_normalization: &IMAGES_NORMALIZATION none
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    masks_normalization: &MASKS_NORMALIZATION none
    masks_output_format_type: &MASKS_FORMAT_TYPE long
    size_transform: sized_crop

val:
  path: *TRAIN_PATH
  masks: classification
  transform:
    size: *SIZE
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: resize

test:
  path: *TRAIN_PATH
  masks: classification
  transform:
    size: *SIZE
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: resize

model:
  arch: efficientnet-b0
  pretreined: False
  encoder_depth: 34
  classes: 19
  loss:
#    - name: mean_dice
#      weight: 0.25
    - name: categorical_cross_entropy
#      gamma: 1
#      class_weights: [0.00898384, 0.37205847, 0.16033528, 0.46362242]
      weight: 1
  metrics:
    - AP
  load_weights: False
#  model_path: /home/kolinko/logs/cam/models/efficientnet-b0-2021-04-04-18-13-33.pth
  model_path: /home/kolinko/logs/cam/models/efficientnet-b0-2021-04-02-16-45-39.pth



pred_dir: /datasets/kolinko/hpa_pred/cam
num_epochs: 50
batch_size: 20
optimizer:
  name: adam
  lr: 0.003
  weight_decay: 0.000001

scheduler:
  name: step
  gamma: 0.2
  step_size: 6

monitor:
  method: epochs
  interval: 1000

experiment_name: resnet50-2021-03-23-13-05-50

args:
  seed: 0
  num_workers: 8
  mode: normal
  lr: 0.1
  wd: 0.0001
  nesterov: True
  image_size: 224
  print_ratio: 0.1
  num_pieces: 4
  loss_option: cl_pcl_re
  level: feature
  re_loss: L1_Loss
  alpha: 1.0
  alpha_schedule: 0.50
  re_loss_option: masking
