---
project: hpa_challenge
task: classification
log_path: /home/kolinko/logs/hpa

devices:
  - 'cuda:1'
#  - 'cuda:1'

train:
  path: &TRAIN_PATH /datasets/kolinko/balanced_data/
  transform:
    size: &SIZE 224
    augmentation_scope: weak
    images_normalization: &IMAGES_NORMALIZATION none
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    masks_normalization: &MASKS_NORMALIZATION none
    masks_output_format_type: &MASKS_FORMAT_TYPE long
    size_transform: crop_or_resize

val:
  path: /datasets/kolinko/test_balanceed_data/
  masks: classification
  transform:
    size: 256
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: resize

model:
  arch: resnet50
  encoder_depth: 34
  classes: 19
  loss:
#    - name: mean_dice
#      weight: 0.25
    - name: categorical_cross_entropy
#      gamma: 1
#      class_weights: [0.00898384, 0.37205847, 0.16033528, 0.46362242]
      weight: 1
  metrics:
    - AP

num_epochs: 15
batch_size: 64
optimizer:
  name: adam
  lr: 0.003
  weight_decay: 0.000001

#scheduler:
#  name: plateau
#  mode: max
#  patience: 2
#  factor: 0.5
#  min_lr: 0.0000001

scheduler:
  name: step
  gamma: 0.2
  step_size: 6

monitor:
  method: epochs
  interval: 1000

experiment_name: resnet50-2021-03-23-13-05-50
