---
project: brats_challenge
task: segmentation_3d
log_path: /home/ostap/logs/brats

devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'

train:
  path: /datasets/extra_space/brats/preprocessed/train_3d
  transform:
    size: &SIZE 128
    augmentation_scope: none
    images_normalization: &IMAGES_NORMALIZATION default
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    masks_normalization: &MASKS_NORMALIZATION none
    masks_output_format_type: &MASKS_FORMAT_TYPE long
    size_transform: crop

val:
  path: /datasets/extra_space/brats/preprocessed/val_3d
  masks: segmentation
  transform:
    size: 240
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: none

model:
  arch: unet_3d
  input_channels: 4
  classes: 4
  loss:
    - name: mean_iou
      weight: 0.5
    - name: categorical_cross_entropy
      gamma: 1
      class_weights: [0.00398384, 0.37205847, 0.16033528, 0.46362242]
      weight: 0.5
  metrics:
    - dice

num_epochs: 50
batch_size: 4
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.000001

#scheduler:
#  name: plateau
#  mode: max
#  patience: 2
#  factor: 0.5
#  min_lr: 0.0000001

scheduler:
  name: step
  gamma: 0.2
  step_size: 10

monitor:
  method: epochs
  interval: 5
