---
project: brats_challenge
task: segmentation_vae
log_path: /mnt/logs/brats

devices:
  - 'cuda:0'
  - 'cuda:1'
  - 'cuda:2'
  - 'cuda:3'

train:
  path: /mnt/brats/preprocessed/train_3d
  transform:
    size: &SIZE 112
    augmentation_scope: none
    images_normalization: &IMAGES_NORMALIZATION custom
    images_output_format_type: &IMAGES_OUTPUT_FORMAT_TYPE float
    masks_normalization: &MASKS_NORMALIZATION none
    masks_output_format_type: &MASKS_FORMAT_TYPE long
    size_transform: crop

val:
  path: /mnt/brats/preprocessed/val_3d
  masks: segmentation
  transform:
    size: 240
    augmentation_scope: none
    images_normalization: *IMAGES_NORMALIZATION
    images_output_format_type: *IMAGES_OUTPUT_FORMAT_TYPE
    masks_normalization: *MASKS_NORMALIZATION
    masks_output_format_type: *MASKS_FORMAT_TYPE
    size_transform: none

model:
  arch: unet_3d_vae
  input_channels: 4
  classes: 4
  loss:
    - name: mean_dice
      weight: 0.4
    - name: categorical_cross_entropy
      class_weights: [0.00698384, 0.37205847, 0.16033528, 0.46362242]
      weight: 0.6
  vae_loss:
    mse_weight: 0.1
    parametric_kl_weight: 0.1
  metrics:
    - dice

num_epochs: 150
batch_size: 4
optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.000001

scheduler:
  name: step
  gamma: 0.5
  step_size: 20

monitor:
  method: epochs
  interval: 150
